version: '3.8'

services:
  app:
    image: chat_app_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat_app
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
